name: ctcorenet
channels:
  - conda-forge
  - nodefaults
dependencies:
  - dvc~=3.56.0
  - jupyterlab~=4.3.0
  - labelme~=5.2.1
  - onnx~=1.17.0
  - pyqt~=5.15.9
  - python=3.11
  - pytorch~=2.4.1
  - lightning~=2.4.0
  - torchvision~=0.19.1
