# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Test CTCoreNet

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-24.04
    defaults:
      run:
        shell: bash -l {0}

    steps:
    - name: Checkout current git repository
      uses: actions/checkout@v4.2.2

    - name: Setup Miniconda
      uses: conda-incubator/setup-miniconda@v3.0.4
      with:
        conda-solver: libmamba
        channels: conda-forge
        activate-environment: ctcorenet
        environment-file: environment-linux-64.lock
        show-channel-urls: true

    - name: Display virtualenv and installed package information
      run: |
        conda info
        conda list

    # - name: Code Quality
    #   run: black . --check

    - name: Pull test data from dvc remote
      run: |
        dvc pull
        ls -lhR data/

    - name: Test reproducibility of entire ML pipeline
      run: dvc repro
