# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Test CTCoreNet

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-20.04
    defaults:
      run:
        shell: bash -l {0}

    steps:
    - name: Checkout current git repository
      uses: actions/checkout@v2.3.4

    - name: Setup Miniconda
      uses: conda-incubator/setup-miniconda@v2.1.1
      with:
        mamba-version: "*"
        channels: conda-forge
        activate-environment: ctcorenet
        environment-file: environment-linux-64.lock
        show-channel-urls: true

    - name: Display virtualenv and installed package information
      run: |
        conda info
        conda list

    - name: Code Quality
      run: conda run black . --check
